### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by meichelman** [btjaden/TargetRNA3#5]
I am trying to add a genome and I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'RNAplfold_results/NC_000964.3____dnaA.fa'

I get the same error when I try adding the example genome (the command being "python AddGenome.py -a GCF_000009045.1"). The RNAplfold_results folder is there but it is empty. Any ideas as to why the folder does not contain the necessary files? Thank you.

**Comment by btjaden** [comment]
Thanks for raising this. I'm not sure where the problem lies, but there are a couple of possibilities for narrowing down the issue. First, I suggest checking that all five helper tools are correctly installed and executable, e.g., try executing "./blastn -h" and "./blastp -h" and "./blastdb_aliastool -h" and "./RNAplex -h" and "./RNAplfold -h" to verify that each is executable. Assuming all five are verified (and this isn't the issue), I would check if the problem is with downloading the relevant data files or analyzing the data files once downloaded. To check this, download the four data files (e.g., for Bacillus subtilis) from [here](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/009/045/GCF_000009045.1_ASM904v1/). The four files are *.genomic.fna.gz, *.protein.faa.gz, *.feature_table.txt.gz, and *.rna_from_genomic.fna.gz. Place these four files in a directory, e.g., MyGenome. Finally, execute python AddGenome.py -g MyGenome. If this works, then the issue is with automatically downloading the four data files. If not, then the issue is with executing the 5 helper tools on these 4 downloaded files. This may or may not solve the problem, but hopefully it will narrow it down.

**Comment by meichelman** [comment]
I verified the 5 helper tools are correctly installed and executable using ./tool -h, no issues there. I also set up a MyGenome directory and downloaded the data files and still have the same issue.

I tried reinstalling (with homebrew) BLAST and ViennaRNA to ensure I have the latest versions. The BLAST executables are all version 2.15.0 and the ViennaRNA executables are version 2.4.17.

I continue to get the same error: "FileNotFoundError: [Errno 2] No such file or directory: 'RNAplfold_results/NC_000964.3____dnaA.fa'". It is worth noting when I run "python AddGenome.py -g Genomes/MyGenome" the error I get is with "NC_000964.3____dnaA.fa" but when I run with python3 the error is with "NC_000964.3____purS.fa". Additionally, I can run python3 with the version (3.12.3) installed on my device but I do not have python so I have been using a conda environment (also 3.12.3). The RNAplfold_results directory remains empty either way.

**Comment by btjaden** [comment]
Hmm... sorry for this issue. I'm not sure why the RNAplfold_results directory is empty. With the error message, do you know what line number in AddGenome.py is causing the error?

**Comment by meichelman** [comment]
Yes the error is with line 483:
"""
Traceback (most recent call last):
  File "/Users/meichelman/anaconda3/envs/targetrna3/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/meichelman/anaconda3/envs/targetrna3/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "TargetRNA3/AddGenome.py", line 483, in run_RNAplfold
    with open(GENOME_DIR + RNAPLFOLD_DIR + accession + '____' + mRNA_name + '.fa', 'w') as out_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'RNAplfold_results/NC_000964.3____cutI.fa'
"""
Is it possible the error has something to do with python being called in the conda environment, but the program and supporting files are in a different location?

**Comment by btjaden** [comment]
Thanks, this is helpful. From the error message, I see it is spawning multiple threads, which is to be expected since this is the default behavior. Just to rule this out as the cause of the error, I would suggest executing it with a single thread (it should give the exact same results as with multiple threads but it may take a bit longer to run). You can use the flag -n_threads:
`    python AddGenome.py -a GCF_000009045.1 -n_threads 1`
If this doesn't fix the issue, then my best guess is that it is searching for files in the wrong place (possibly because of the environment, as you mention, though I'm not sure). At line 483, it looks to me like it is trying to create the file `RNAplfold_results/NC_000964.3____****.fa` instead of the file `Genomes/GCF_000009045.1/RNAplfold_results/NC_000964.3____****.fa` It seems like it is missing the initial `Genomes/GCF_000009045.1/` path, but I'm not sure why.

**Comment by meichelman** [comment]
I ran with one thread as you described above and that worked! It ran to completion and output the message "DONE.		New files have been generated in Genomes/MyGenome/". Thank you very much for the help!

**Comment by btjaden** [comment]
Great, glad it's working!
